### ISSUE TITLE
About Flooding attack code 

### ISSUE THREAD

**Issue by YSJE** [crond-jaist/iotrain-sim#2]
Hello I want to ask about your flooding attack code. 
I want to edit send interval of flooding attacker but int this repository it has only .sky file.
Can I get udp-sender-flooding_attack.c file?
I tried many of cooja flooding attacker code, but your code is most efficiently to saw waste the power resources to vicitim node.
Please give me answer. 
Thank you.

**Comment by crond-jaist** [comment]
Hi,
As far as I remember we did this attack by modifying only the files `rpl-private.h` and `rpl-timers.c` which are included in the repository. Please check the tutorial and references for a brief explanation of the mechanism, and the files to see the implementation.
Since we did not modify the `udp-sender.c` file, it is not included in the repository, but you are free to change the file that comes with Cooja if you want to see how it affects the results.
Best wishes,
Razvan

**Comment by crond-jaist** [comment]
Closed since there was no follow-up for four months.
